version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.dockerfile
    ports: 
      - 8080:8080
      - 50000:50000
    volumes: 
      - $PWD/jenkins_home:/var/jenkins_home
      - $PWD:/app
  website:
    build: .
    ports:
      - 80:80
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5901:5900
  integration-tests:
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - "$PWD:/app"
    build:
      context: .
      dockerfile: rspec.dockerfile
    command:
      - --pattern
      - /app/spec/integration/*_spec.rb
  unit-tests:
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - "$PWD:/app"
    build: 
      context: .
      dockerfile: rspec.dockerfile
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb
  terraform:
    build:
      context: .
      dockerfile: terraform.dockerfile
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
      AWS_REGION: $REGION
      AWS_DEFAULT_REGION: eu-central-1
    volumes:
      - "$PWD:/app"
    working_dir: /app
  aws:
    image: xueshanf/awscli
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
      AWS_REGION: $REGION
      AWS_DEFAULT_REGION: eu-central-1
    volumes:
      - "$PWD:/app"
    working_dir: /app

